agent_type: judge

model:
  name: phi4-mini
  temperature: 0.2
  max_context_tokens: 131072
  max_turn_tokens: 4096

processor:
  max_raw_length: 512
  min_raw_length: 64
  concatenate_small_segments: true

dialogue:
  max_turns: 12
  memory_limit: 24
  trim_strategy: rolling

judge:
  model_name: phi4-mini
  temperature: 0.2
  max_retries: 3
  judges: 5
  threshold: 0.69

regex_filters:
- pattern: "^[\\s\\n\\r]*$"
  reason: "empty or whitespace-only content"

- pattern: "^[^a-zA-Z0-9]{10,}$"
  reason: "content with only symbols/punctuation"

templates:
  system: judge_system
  judge: segment_judge

format:
  expected_fields: [ score, status, reason ]
  strict_line_count: 3
  parse_strategy: regex

logging:
  verbosity: debug
  track_consensus: true
  return_all_passes: false
  log_queries: true
  log_responses: true
