agent_type: selfcrit

model:
  name: phi4-mini
  temperature: 0.2
  improve_temperature: 0.8
  max_context_tokens: 131072
  max_turn_tokens: 4096

processor:
  max_raw_length: 512

dialogue:
  max_turns: 12
  memory_limit: 24
  trim_strategy: rolling

critique:
  threshold: 0.69
  discard_threshold: 0.25
  passes: 3
  max_retries: 3
  format_enforcement: strict
  enable_followups: true

judge:
  model_name: phi4-mini
  temperature: 0.2
  max_retries: 3
  passes: 3
  threshold: 0.69
  discard_threshold: 0.25

improver:
  model_name: phi4-mini
  temperature: 0.8
  max_retries: 2
  max_turns: 6

regex_filters:
- pattern: "\\b\\w{40,}\\b"
  reason: "long token, likely noise"

- pattern: "\\S{25,}"
  reason: "long unspaced word"

templates:
  system: selfcrit_system
  critique: segment_critique
  followup: segment_followup
  consensus_dispute: segment_consensus_dispute

format:
  expected_fields: [ score, status, reason ]
  strict_line_count: 3
  parse_strategy: regex

logging:
  verbosity: debug
  track_consensus: true
  return_all_passes: false
  log_queries: true
  log_responses: true
